fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class:     Application\UserBundle\Entity\User

    from_email:
        address: "%mailer_sender_email%"
        sender_name: "%mailer_sender_name%"
    group:
        group_class:   Application\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    registration:
        confirmation:
            enabled:  true
#            template: ApplicationUserBundle:Registration:email.html.twig
    resetting:
        retry_ttl: 7200 # Value in seconds, logic will use as hours
        token_ttl: 86400
        email:
            from_email:
                address: '%mailer_sender_email%'
                sender_name:    '%mailer_sender_name%'
            template:   '@FOSUser/Resetting/email.txt.twig'
        form:
            type:               FOS\UserBundle\Form\Type\ResettingFormType # or 'fos_user_resetting' on Symfony < 2.8
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword, Default]

    service:
        user_manager: sonata.user.orm.user_manager
        mailer: Core\UserBundle\Mailer\Mailer
