<?php


namespace Core\ClassificationBundle\Admin;


use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\PropertyAccess\PropertyPath;

class CollectionAdmin extends \Sonata\ClassificationBundle\Admin\CollectionAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
	{
		$formMapper->with('label_collections', array('class' => 'col-md-6'));

		$formMapper
			->add('enabled', null, array('required' => false))
			->add('name')
			->add('description', 'textarea', array('required' => false))
		;


		$formMapper->end();

		$formMapper->with('label_additional_settings', array('class' => 'col-md-6'));

		if (interface_exists('Sonata\MediaBundle\Model\MediaInterface')) {
			$formMapper->add('media', 'sonata_type_model_list',
				array('required' => false),
				array(
					'link_parameters' => array(
						'provider' => 'sonata.media.provider.image',
						'context'  => 'sonata_collection'
					)
				)
			);
		};

		$formMapper
			->add(
				'owner',
				'sonata_type_model_list',
				array(
					'required' => false,
					'btn_list'  => 'select',
				),
				array(
					'link_parameters' => array(
						'provider' => 'sonata.media.provider.image',
						'context'  => 'sonata_collection'
					)
				)
			);

		$formMapper->end();
	}

	public function generateUrl($name, array $parameters = array(), $absolute = false)
	{
		return parent::generateUrl($name, $parameters, $absolute); // TODO: Change the autogenerated stub
	}
}
