index:
    path: /
    controller: App\Controller\DefaultController::index


frontend_security:
    resource: '@FOSUserBundle/Resources/config/routing/security.xml'

frontend_profile:
    resource: '@FOSUserBundle/Resources/config/routing/profile.xml'
    prefix: /profile

frontend_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /resetting
